kind = "web"
previewPath = "/"
title = "StyleZone Store"
version = "1.0.0"
id = "artifacts/store"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 3001

[services.development]
run = "pnpm --filter @workspace/store run dev"

[services.production]
build = ["pnpm", "--filter", "@workspace/store", "run", "build"]
run = ["pnpm", "--filter", "@workspace/store", "run", "start"]
serve = "server"

[services.env]
PORT = "3001"
